import type { Metadata } from "next"
import "./globals.css"
import { Toaster } from "./components/ui/sonner"
import Footer from "./components/footer"
import AuthProvider from "./_providers/auth"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className="antialiased">
        <AuthProvider>
          <div className="flex h-full flex-col"> {/*Classes necessárias para deixar o footer sempre em baixo e o conteúdo principal ocupando todo o espaço  central da tela*/}
            <div className="flex-1"> {/*Esta também é importante para fazer o efeito de cima (OBS: preicsa de outro estilo que fica no arquivo globals.css) */}
              {children}
            </div>
            <Footer/>
          </div>
        </AuthProvider>
        <Toaster/>
      </body>
    </html>
  )
}
